reporting.py

labelling of turbulence and wind speed on the axes

matrix axis label

---

README.md
configuration.py
dataset.py
reporting.py

Application of a time based filter. see read me for example.
Can be used to exclude data affected by noise modes at certain times of the day, days of the week, and months of the year.

Time Filter

---

Analysis.py
configuration.py
dataset.py
pcwg_tool.py

Fixes to calibration filtering and GUI auto scrolling.
#20 
#28

Bug fixes 

---

Analysis.py
configuration.py
dataset.py

Fix filtering after last week's merge conflicts.

Fix filtering

---

configuration.py
dataset.py

https://github.com/peterdougstuart/PCWG/commit/bff828bf0e015adb128d931ce669355a37db5e5e
ToD filter selection by getting all children of <CalibrationFilters> rathers than those named <CalibrationFilter>.
https://github.com/peterdougstuart/PCWG/commit/b5daf5d85f348b8f11f8a4a7642e30ef9d339918
Explicit handling of start and end times in ToD Filtering

Filtering Changes

---

Analysis.py
binning.py
configuration.py
dataset.py
pcwg_tool.py
reporting.py

Fixing issues #35 #34 
Adds more plots using turbulence correction.
creation of turbulence corrected power curve and reporting of it if exists
addition of scatter matric to measure the energy in the scatter.

Issue fixes + Turbulence corrected power curve

---

Analysis.py
configuration.py

fixed issue #16  using .strip() and tested.
Enhancement also for iterating over analysis files.

White space fix

---

configuration.py
dataset.py

@lcameron05  #50 change as discussed.
and GUI fixes including #51

Various fixes to GUI and AEP calc

---

Analysis.py

help dialogue for column picking

help dialogue for column picking

---

configuration.py
pcwg_tool.py

Console error messages are now displayed in red.

Console error message

---

Analysis.py
aep.py
configuration.py
dataset.py
pcwg_tool.py
plots.py
turbine.py

Moved plotting code to  new file as it was getting a bit too large and confusing.
Fixed concurrent dataset issue #57 .

Move plotting and fix issue

---

Analysis.py
pcwg_tool.py
reporting.py

Small GUI fixes. Scatter metric calculated by direction but not
reported.

GUI fixes, Scatter metric by direction

---

Analysis.py
aep.py
reporting.py

lingering changes I forgot to commit.

increased AEP reporting

---

reporting.py

Fixes bug for specified calibration.
If more than one dataset with calibration used they are reported on
separate sheets.

Report fix

---

aep.py

AEP annualisation

---

Analysis.py

AEP Bug Fix

---

dataset.py

calculateMultiPointShear() fix

---

dataset.py

WS must be defined at two heights for shear to be defined

Shear WS measurements requirement

---

Analysis.py

Turbulence padding above cut out

---

Analysis.py
pcwg_tool.py
reporting.py

Option to pad incomplete power curve bins above last complete bin with
rated power added.

Rated Power Padder

---

aep.py

Now performed at source of rebinned distribution as opposed to during
AEP calc. Fix to the method for LCB case which was not included in the
report anyhow.

Wind distribution annualisation

---

pcwg/reporting/reporting.py

Changed reporting.py to reflect this.
Fixes #152

Turbine meta data moved to dataset config

---

pcwg/configuration/dataset_configuration.py
pcwg/configuration/preferences_configuration.py
pcwg/core/dataset.py
pcwg/core/exception_type.py
pcwg/core/share.py
pcwg/exceptions/handling.py
pcwg/gui/dataset.py
pcwg/gui/exception_type.py
pcwg/gui/grid_box.py
pcwg/gui/root.py
pcwg/reporting/reporting.py

Shear calibration can be setup through the UI.
Generalised exceptions handling class added but not widely used
throughout code yet.
Bug fixes to reporting including #148

Exception Handling & Reporting Improvements. Shear calibration in UI.

---

pcwg/core/share.py
pcwg/gui/dataset.py
pcwg/gui/grid_box.py
pcwg/gui/root.py

Fixes #149
Some additional Pythonic indentation

Exception handling

---

extractor.py

Fix extractor bug

---

pcwg/configuration/base_configuration.py
relative_path_test.py

Report fix when using `TimeOfDayFilter`
Unit test for `SinglePathManager` behaviour

pulling lcameron05/master

---

pcwg/core/analysis.py
pcwg/reporting/plots.py

Plus minor improvements to sensitivity analysis output

Fixes #164

---

pcwg/core/dataset.py
pcwg/reporting/plots.py

and formatting of sensitivity analysis plot

Improved empty cols error message

---

pcwg/gui/dataset.py

pythonic indentation
